proxy_ssl:
  cert: /app/certs/proxy.crt
  key: /app/certs/proxy.key

receivers:
  - name: vmcluster
    label_name: job
    label: elastic_exporters
    prom: "https://192.168.100.113:8427"
    cert: /app/vmcluster/vmcluster.crt
    key: /app/vmcluster/vmcluster.key
    prom_auth:
      user: "userA"
      password: "userApass"
      cert: /app/certs/prom1-client.crt
      key: /app/certs/prom1-client.key

  - name: prometheus
    label_name: job
    label: prometheuss
    prom: "http://192.168.100.118:9090"
    auth:
      user: "userB"
      password: "userBpass"

  - name: vmsingle
    prom: "http://192.168.100.108:8428"
    verify: false
