services:
  hesione:
    image: duoluotianshi/hesione:latest
    container_name: hesione
    ports:
      - "8000:8000"
    volumes:
      - ./config.yml:/app/config.yaml:ro
    restart: unless-stopped
