services:
  hesione:
    image: duoluotianshi/hesione:latest
    container_name: hesione
    ports:
      - "8000:8000"
    volumes:
      - ./config.yaml:/app/config.yaml:ro
      - ./certs:/app/certs:ro
      - ./vmcluster:/app/vmcluster:ro
    restart: unless-stopped
